### ISSUE TITLE
E-Mails mit Whitelist abgleichen?

### ISSUE THREAD

**Issue by rustykowski** [eS-IT/downloadmail#1]
Hallo Patrick,
wäre es auch möglich, die eingegebene Mailadresse gegen eine Whitelist abzugleichen?
Hintergrund: Ein Kunde will sich so den Login ersparen. Sensible Dokumente bzw. Downloadlinks sollen nur per Mail an eine begrenzte Gruppe von Menschen (z.B. Mitglieder) gesendet werden.

**Comment by eS-IT** [comment]
Eine Whitelist ist bis jetzt nicht vorgesehen. Möglich wäre es aber auf jeden Fall, müsste man nur implementieren.

**Comment by zonky2** [comment]
@rustykowski bei Mitgliedern mit Login könnte man Formular usw. komplett in den geschützten Bereich einsetzen - ich würde eher an einen Zugangstoken denken, das kann man aber selbst im Formular abprüfen

**Comment by eS-IT** [comment]
Da vermutlich nicht gewünscht ist, dass die Personen dann für jeden Download wieder das Formular ausfüllen, sehe ich keine große Schnittmenge mit dieser Erweiterung. Es lässt sich bestimmt eine Lösung finden, aber es ist vermutlich einfacher ohne DownloadMail.

@rustykowski Wenn Du Hilfe bei der Umsetzung brauchst, schicke mir gerne eine Mail an info@easySolutionsIT.de.

Da eine Umsetzung im Rahmen der Erweiterung nicht angedacht ist, mache ich hier zu.

**Comment by rustykowski** [comment]
Danke euch! Ich konnte die Anforderung (ohne Login!) letztlich mit der Erweiterung richardhj/contao-email-token-login lösen.
