### ISSUE TITLE
Download-Modul: Problem mit $requestTime

### ISSUE THREAD

**Issue by lizardat** [eS-IT/downloadmail#10]
Hallo.
Wenn man im Download-Modul die "Zeit bis zum Download" leer lässt, funktioniert es.
Ist dort allerdings ein Wert eingetragen, z.B. 5, kommt diese Fehlermeldung im prod.log:

`[2023-06-02T12:06:26.794694+02:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Esit\Downloadmail\Classes\Events\OnManageDownloadEvent::setRequestTime(): Argument #1 ($requestTime) must be of type string, int given, called in /var/www/clients/client88/webxx/web/vendor/esit/downloadmail/Classes/Listener/OnManageDownloadListener.php on line 276" at /var/www/clients/client88/webxx/web/vendor/esit/downloadmail/Classes/Events/OnManageDownloadEvent.php line 318 {"exception":"[object] (TypeError(code: 0): Esit\\Downloadmail\\Classes\\Events\\OnManageDownloadEvent::setRequestTime(): Argument #1 ($requestTime) must be of type string, int given, called in /var/www/clients/client88/webxx/web/vendor/esit/downloadmail/Classes/Listener/OnManageDownloadListener.php on line 276 at /var/www/clients/client88/webxx/web/vendor/esit/downloadmail/Classes/Events/OnManageDownloadEvent.php:318)"} []`

(Contao 4.13.24, PHP 8.1.18)

**Comment by eS-IT** [comment]
Mit Version 3.2.1 behoben.

**Comment by lizardat** [comment]
Danke!!!
Etwas ähnliches scheint bei der bcc-E-Mail-Adresse aufzutreten, wenn das Feld leer bleibt: 
`[2023-06-02T12:28:10.537438+02:00] request.CRITICAL: Uncaught PHP Exception TypeError: "unserialize(): Argument #1 ($data) must be of type string, null given" at /var/www/clients/client88/webxx/web/vendor/esit/downloadmail/Classes/Listener/OnManageFormListener.php line 364 {"exception":"[object] (TypeError(code: 0): unserialize(): Argument #1 ($data) must be of type string, null given at /var/www/clients/client88/webxx/web/vendor/esit/downloadmail/Classes/Listener/OnManageFormListener.php:364)"} []`

**Comment by eS-IT** [comment]
Mit Version 3.2.2 behoben.
