### ISSUE TITLE
Readme und Beschreibung für den CM anpassen

### ISSUE THREAD

**Issue by zonky2** [eS-IT/downloadmail#2]
Aus dem Text geht nicht hervor, was die Erweiterung macht ;-)

z. B. "DownloadMail v2 ist ein Erweiterung für das Open Source CMS Contao und ermöglicht, den Download einer geschützten Datei erst nach dem Absenden eines beliebigen Formulars."

**Comment by eS-IT** [comment]
Erledigt

**Comment by zonky2** [comment]
prima - vor "bitte" ein Leerzeichen

**Comment by eS-IT** [comment]
Auch erledigt
