### ISSUE TITLE
E-Mail-Adresse wird trotz erfolgreicher Weiterleitung nicht übertragen (Problem mit Autocomplete?)

### ISSUE THREAD

**Issue by Shoekrates** [eS-IT/downloadmail#3]
Hallo Patrick,
danke für diese Erweiterung, die grundsätzlich gut funktioniert. Ich laufe aber in ein Problem, dass ich mir nicht wirklich erklären kann. 
Manchmal wird beim Absenden des Formulars der Wert des E-Mail-Feldes nicht übergeben, so dass der Besucher zwar auf der Erfolgs-Weiterleitungsseite des Formulars landet, aber keine E-Mail bekommt. In der Downloadstatistik steht dann so etwas:

`[23.02.2021 07:08] - 0 Downloads`
statt
`[23.02.2021 07:08] name@email.de - 0 Downloads`

Ich kann es (wahrscheinlich) auf die Autocomplete-Funktion des Browsers zurückführen. Alle Tests mit händischer Eingabe waren erfolgreich. Lässt sich der Besucher beim Befüllen des Feldes durch den Browser helfen und tippt oder klickt nur den Vorschlag zum Befüllen des Feldes an, dann resultiert das **manchmal** in dem oben beschriebenen Verhalten. Leider nicht immer.
Beobachten konnte ich es vor allem mit mobilen Browsern, z. B. Chrome auf Android oder Safari auf iOS, aber auch macOS.

System:
Contao 4.9.12, DownlaodMail 2.1.4. 
Das Formular enthält neben dem Inputfeld für E-Mail-Adresse (Validierung auf E-Mail-Adresse + Pflichtfeld) nur die Sicherheitsfrage von Contao.

Ich habe bereits folgendes probiert:
- Setzen von Attribut autocomplete="off" in FORM-Tag und INPUT-TAG (über jeweils eigene Templates). Leider halten sich hier die Browser nicht wirklich dran.
- Deaktivierung der HTML5-Validierung im Formular
- Zusätzliche Live-Validierung des Feldes über trilobit-gmbh/contao-formvalidation-bundle
- Automatisches Setzen des Fokus, sobald das Inputfeld beim Scrollen im sichtbaren Bereich ist

Leider alles ohne Erfolg. Hast du ggf. noch eine Idee?

**Comment by eS-IT** [comment]
Hallo Christian,
die Formulare sind normale Formulare aus dem Formulargenerator. Die Erweiterung setzt erst bei der Verarbeitung der abgesendeten Werte an. Ich wüsste deshalb nicht, was ich tun könnte, wenn die Validierung ausgehebelt und keine Daten übertragen werden. Dies scheint mir eine Sache zwischen Contao und dem Browser zu sein. Mehr als das, was Du versucht hast, weiß ich auch nicht. Ich bin aber auch kein Frontendspezialist. Sorry!

**Comment by Shoekrates** [comment]
Danke für die schnelle Reaktion. Schade. Dann gehe ich mal weiter auf die Suche auf Basis der Contao Core Funktionen. Wenn ich was rausfinde, melde ich mich.

**Comment by eS-IT** [comment]
Da hier seid 2,5 Jahren nichts passiert ist, mache ich das Ticket zu.
