### ISSUE TITLE
Mehrsprachiges Setup

### ISSUE THREAD

**Issue by BitWhatElse** [eS-IT/downloadmail#4]
Vielen Dank für diese tolle Erweiterung, macht genau das was ich möchte. Ich habe eine zweisprachige Seite mit DE und EN. 
Für DE funktioniert alles, im EN Seitenbaum funktioniert die Linkgenerierung irgendwie nicht und die Downloadseite wird nicht gefunden. Aufgefallen ist mir, dass die Konfiguration der Erweiterung nur im Seitenbau für DE angelegt wurde. Im Seitenbau für EN fehlt die Konfiguration.

Kann die Erweiterung für mehrsprachige Seiten noch verbessert werden?

Logmeldung:
{"exception":"[object] (TypeError(code: 0): Argument 1 passed to Esit\\Downloadmail\\Classes\\Events\\OnManageDownloadEvent::setFeFormLang() must be of the type array, null given, called in ../vendor/esit/downloadmail/Classes/Contao/Modules/ModuleRequestDownload.php on line 71 at ../vendor/esit/downloadmail/Classes/Events/OnManageDownloadEvent.php:182)"}

**Comment by eS-IT** [comment]
> Kann die Erweiterung für mehrsprachige Seiten noch verbessert werden?

Man kann alles machen, wofür Bedarf besteht. Bisher brauchte es wohl noch keiner. Ich kann aber nicht sagen, wann ich dazu komme.

**Comment by eS-IT** [comment]
Ich habe es mir gerade angesehen, der Fehler kommt von der Fehlenden Übersetzung. Es werden nur deutsche Sprachdateien mitgeliefert. Dies werde ich auch nicht ändern, da mein Englisch dafür vermutlich zu schlecht ist. 

Es ist aber leicht möglich Sprachdateien für englisch anzulegen. Es müssen nur die Einträge in [languages/de/default.php](https://github.com/eS-IT/downloadmail/blob/master/Resources/contao/languages/de/default.php#L22) ab Zeile 22 übersetzt werden.

**Comment by BitWhatElse** [comment]
Ok, vielen Dank. Es ist für mich kein Problem einen Beitrag an die Weiterentwicklung zu leisten, wenn ich weiss was zu tun ist.

Muss ich einen neuen Ordner  languages/**en**/ erstellen und die Übersetzungen einpflegen?

**Comment by eS-IT** [comment]
Ja, genau. Das wäre sehr hilfreich. Ich übernehme es dann.

**Comment by BitWhatElse** [comment]
Guten Tag, anbei die englischen Übersetzungen.
---------------------------------------------------------------------
$GLOBALS['TL_LANG']['MSC']['easy_downloadmail']['feform']['mailplaceholder']    = 'Please enter your e-mail address.';
$GLOBALS['TL_LANG']['MSC']['easy_downloadmail']['feform']['submit']             = 'Request';
$GLOBALS['TL_LANG']['MSC']['easy_downloadmail']['feform']['mandatory']          = 'Required field';
$GLOBALS['TL_LANG']['MSC']['easy_downloadmail']['feform']['emaillabel']         = 'E-mail address';
$GLOBALS['TL_LANG']['MSC']['easy_downloadmail']['feform']['blacklisterror']     = 'Unfortunately, no download can be requested with this mail address!';
$GLOBALS['TL_LANG']['MSC']['easy_downloadmail']['feform']['downloaderror']      = 'Unfortunately, no download could be found with this download code!';
$GLOBALS['TL_LANG']['MSC']['easy_downloadmail']['feform']['keyerror']           = 'No download code could be found!';
$GLOBALS['TL_LANG']['MSC']['easy_downloadmail']['feform']['fileerror']          = 'File not found!';
$GLOBALS['TL_LANG']['MSC']['easy_downloadmail']['feform']['downloadstart']      = 'Start download';
$GLOBALS['TL_LANG']['MSC']['easy_downloadmail']['feform']['downloadmessage']    = 'If the download does not start in %s seconds, please use the following link:';
$GLOBALS['TL_LANG']['MSC']['easy_downloadmail']['feform']['downloadtolate']     = 'Unfortunately, this download code has expired. You can request the download again <a href="%s">here</a>.';
$GLOBALS['TL_LANG']['MSC']['easy_downloadmail']['feform']['custrgxperr']        = 'The e-mail address in the %s file cannot be used!';
$GLOBALS['TL_LANG']['MSC']['easy_downloadmail']['feform']['notimeerr']          = 'No request time found!';
---------------------------------------------------------------------
Übersetzungen habe ich mal in languages/en/default.php abgelegt
Leider funktioniert es noch nicht wie gewünscht.. auf der Seite in de ist ok, Seite in en (ist auch Sprachenfallback), wir folgender Fehler im Log eingetragen:
request.CRITICAL: Uncaught PHP Exception TypeError: "Argument 1 passed to Esit\Downloadmail\Classes\Events\OnManageDownloadEvent::setFeFormLang() must be of the type array, null given, called in ../vendor/esit/downloadmail/Classes/Contao/Modules/ModuleRequestDownload.php on line 71" at ../vendor/esit/downloadmail/Classes/Events/OnManageDownloadEvent.php line 182 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Esit\\Downloadmail\\Classes\\Events\\OnManageDownloadEvent::setFeFormLang() must be of the type array, null given

Vielleicht finden sie mal Zeit dies anzuschauen.. Besten Dank schon im voraus. 
Viele Grüsse
Daniel Sutter

**Comment by eS-IT** [comment]
Version 2.1.8 sollte das Problem lösen.

**Comment by BitWhatElse** [comment]
Super, vielen Dank! Wird finden diese Erweiterung sehr gelungen und deckt genau unseren Use-Case ab.
