### ISSUE TITLE
Versenden von Emails nach Abschicken des Formulares nicht möglich

### ISSUE THREAD

**Issue by lk-code** [eS-IT/downloadmail#5]
Nachdem man ein Formular komplett und korrekt ausgefüllt hat und dieses abschickt kommt eine Contao-Fehlerseite. In den Logs ist folgender Fehler zu finden:

`request.CRITICAL: Uncaught PHP Exception ArgumentCountError: "Too few arguments to function Esit\Downloadmail\Classes\Services\Helper\StringHelper::__construct(), 0 passed in ........./mes_contao_v0/var/cache/prod/ContainerKXxvuzf/getDownloadmail_Listener_OnManageFormListener_LoadDownloadFromDbService.php on line 12 and exactly 6 expected" at ........./mes_contao_v0/vendor/esit/downloadmail/Classes/Services/Helper/StringHelper.php line 63 {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function Esit\\Downloadmail\\Classes\\Services\\Helper\\StringHelper::__construct(), 0 passed in ........./mes_contao_v0/var/cache/prod/ContainerKXxvuzf/getDownloadmail_Listener_OnManageFormListener_LoadDownloadFromDbService.php on line 12 and exactly 6 expected at ........./mes_contao_v0/vendor/esit/downloadmail/Classes/Services/Helper/StringHelper.php:63)"} []`

Laut der StringHelper.php werden in der Tat 6 Parameter erwartet. In der generierten getDownloadmail_Listener_OnManageFormListener_LoadDownloadFromDbService.php erfolgt die Initialisierung jedoch komplett ohne Parameter.

**Comment by eS-IT** [comment]
Dann scheint der Code im Cache fehlerhaft zu sein. Leider kann ich mit den genannten Informationen, nicht mehr dazu sagen. Es kann an einer bestimmten Version liegen, oder sonstigen äußeren Einflüssen. Leider kann ich das so nicht beurteilen.

**Comment by lk-code** [comment]
Das habe ich auch erst gedacht und habe im Contao Manager unter Systemwartung den Anwendungscache (prod) gelöscht. später auch um sicher zu gehen den Composer-Cache und den Opcode-Cache. Installiert ist die aktuellste Version 2.1.8. Ansonsten ist nicht wirklich was in Contao installiert.

**Comment by eS-IT** [comment]
Evtl. liegt es an der Contao- oder Symfonyversion. Wie gesagt, ohne das System zu kennen, ist eine Diagnose schwer.

**Comment by eS-IT** [comment]
Scheinbar gab es eine Änderung beim Autowiring. Probier bitte die Version 2.1.9 aus. Ich hoffe die löst das Problem.

**Comment by lk-code** [comment]
Hi,

ich hatte Montag die Version 2.1.7 installiert. Mit der gab es erst mal keine Probleme. Ich habe grade die 2.1.9 installiert. Dort kommt wieder eine Exception. Dieses mal aber eine andere:

<img width="972" alt="image" src="https://user-images.githubusercontent.com/1656571/157396159-8d292a0d-04f7-40cc-b403-1fdfac1fe876.png">

Symfony: 4.4.39
Contao: 4.9.26
Website liegt bei godaddy

**Comment by eS-IT** [comment]
Sollte eigentlich nicht passieren. Ich habe die Erweiterung jetzt auf den QueryBuilder umgestellt, so dass Contao\Database nicht mehr verwendet wird. Version 2.1.11 ist raus.

**Comment by lk-code** [comment]
Ist installiert und es kommt eine andere Exception:

<img width="972" alt="image" src="https://user-images.githubusercontent.com/1656571/157411195-1851b3fa-4eca-4b6b-8e27-97e10eff4de0.png">

**Comment by eS-IT** [comment]
StringHelper ist ein Klasse von Contao. die als Rückgabewert `miexed` hat. Es sollte aber nicht Esit\Downloadmail\Classes\Services\Helper\miexed sein. Ich habe den Rückgabewert an der Stelle auf string geändert.

**Comment by lk-code** [comment]
Also gut ist zumindest, dass keine Fehler mehr geworfen werden. Allerdings geht keine Email raus und in der Download-Übersicht steht auch keine Email aus dem Formular.

<img width="331" alt="image" src="https://user-images.githubusercontent.com/1656571/157433027-06cb3f87-05cd-431c-9e06-e170e2736322.png">

**Comment by eS-IT** [comment]
Da es bei mir funktioniert, weiß ich leider nicht, wo ich da ansetzen soll.

**Comment by lk-code** [comment]
Ich werde nochmal schauen, ob irgendwas mit den Formularen ist. Das Problem für dieses Issue ist ja aber erstmal gelöst. Danke dafür.

**Comment by lk-code** [comment]
Es gibt doch noch einen Punkt 🙈. Im Backend kann man nicht auf die Details bestehender Downloads klicken:

<img width="497" alt="image" src="https://user-images.githubusercontent.com/1656571/157438487-97aeadb8-1315-4cd7-be33-e14e91a77e00.png">

Der Fehler:

<img width="972" alt="image" src="https://user-images.githubusercontent.com/1656571/157438349-4e292392-5c8f-43c8-a482-961ad32d596e.png">

**Comment by lk-code** [comment]
Gibt es weitere Informationen die helfen könnten?

**Comment by eS-IT** [comment]
> Gibt es weitere Informationen die helfen könnten?

Nicht wirklich. Für solche Fehler gibt es eigentlich Softwaretests. Leider ist die Erweiterung so alt, dass ich damals noch keine geschrieben habe und jetzt einfach nicht mehr die Zeit finde.

**Comment by lk-code** [comment]
Das Gefühl kenne ich 😅 Ich zwinge mich mittlerweile dazu. Aber meißtens fehlt einfach die Zeit.

**Comment by eS-IT** [comment]
Eigentlich macht es mir Spaß und bei aktuellen Projekten schreibe ich immer Tests. Leider fehlt mir im Augenblick die Zeit um ausgiebiger an Open Source Projekten zu arbeiten.

**Comment by lk-code** [comment]
Ich schaue da auch ein wenig rein. Aber PHP, Symfony ist bei mir auch schon Jahre her. Damals mit Shopware.

**Comment by lk-code** [comment]
Ich konnte erst jetzt das Update 2.1.13 installieren. Es gibt beim Klick auf die Download-Detailseite im Backend folgenden Fehler:

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/1656571/157462225-16c31ca7-ae2b-4d95-809f-e828109ee7fe.png">

**Comment by eS-IT** [comment]
Das liegt an der PHP-Version. Mit PHP 8 sollte es funktionieren.

**Comment by lk-code** [comment]
Wir können leider nicht auf PHP 8 upgraden. Auf dem Server liegen noch andere Websites von uns die an 7.4 gebunden sind.

**Comment by eS-IT** [comment]
PHP 7.4 ist outdated und bekommt nur noch Securityfixes. Ab November ist dann ganz Schluss. Eigenlicht würde ich die Erweiterung gerne auf PHP 8 heben, wenn ich sie jetzt schon mal anfasse.

**Comment by lk-code** [comment]
Ich habe das grade bei uns auf dem Server abgeändert (mit is_null). Danach kommen weitere Fehler.

<img width="782" alt="image" src="https://user-images.githubusercontent.com/1656571/157464680-aeb4ec0f-6c7c-4663-8fd3-6630ad50e4e2.png">

Ich werde jetzt erstmal wieder auf 2.1.7 geheb, damit die Seite läuft.

**Comment by eS-IT** [comment]
Dann wird das Quellformular nicht gefunden.

**Comment by eS-IT** [comment]
Steht denn in der DB bei dem betreffenden Datensatz in `tl_dm_downloads.formid` die Id des Quellformulars?
