### ISSUE TITLE
Error creating new pages

### ISSUE THREAD

**Issue by johannes-bittner** [eS-IT/downloadmail#6]
After installation, when I try to create a new page, I get the following error message in the backend: 

`An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1364 Field 'mailtext' doesn't have a default value`

[Contao 4.13, PHP 8]

**Comment by eS-IT** [comment]
Fixed in Version 3.0.3

**Comment by johannes-bittner** [comment]
Awesome - thank you!
