### ISSUE TITLE
Fehler im Frontend

### ISSUE THREAD

**Issue by lizardat** [eS-IT/downloadmail#7]
Leider funktioniert es bei mir nicht (Contao 4.13.12, PHP 8.1.11)... 

Eintrag im log:

`[2022-11-10T11:20:04.020861+01:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load class "Event" from namespace "Symfony\Component\EventDispatcher". Did you forget a "use" statement for e.g. "Symfony\Contracts\EventDispatcher\Event", "Spatie\SchemaOrg\Event", "Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Event" or "FOS\HttpCache\Event"?" at /var/www/clients/xxxxxxxxx/web/vendor/esit/downloadmail/Classes/Events/OnManageDownloadEvent.php line 26 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\ClassNotFoundError(code: 0): Attempted to load class \"Event\" from namespace \"Symfony\\Component\\EventDispatcher\".\nDid you forget a \"use\" statement for e.g. \"Symfony\\Contracts\\EventDispatcher\\Event\", \"Spatie\\SchemaOrg\\Event\", \"Nelmio\\SecurityBundle\\ContentSecurityPolicy\\Violation\\Event\" or \"FOS\\HttpCache\\Event\"? at /var/www/clients/xxxxxxxxx//web/vendor/esit/downloadmail/Classes/Events/OnManageDownloadEvent.php:26)"} []`

**Comment by eS-IT** [comment]
Fix in Version 3.0.6
