### ISSUE TITLE
Modul

### ISSUE THREAD

**Issue by kissinger999** [eS-IT/downloadmail#8]
Wo finde ich das Modul easy_Downloadmail und wie bunde ich es ein?

Danke!

**Comment by eS-IT** [comment]
Das Modul wird unter Themes > Module erstellt und über das Seitenlayout oder ein Artikel eingebunden.

**Comment by kissinger999** [comment]
Hallo!

Danke für die Antwort. Ist mit "easy_Downloadmail" das Modul "Download" vom Contao-Core gemeint? In der Liste der Module kann ich kein Modul "easy_Downloadmail" finden.

**Comment by eS-IT** [comment]
Hallo!
Nein es ist schon ein Modul vom Typ "easy_Downloadmail" gemeint:

![easy_Downloadmail](https://user-images.githubusercontent.com/1199106/217779698-7f8da455-5a38-49fa-b528-f76b816b6ba7.png)

**Comment by kissinger999** [comment]
Jetzt habe ich es gefunden und kann die Erweiterung testen! 
Vielen Dank Patrick!
