### ISSUE TITLE
Problem mit Suffix

### ISSUE THREAD

**Issue by kissinger999** [eS-IT/downloadmail#9]
Hallo Patrick!

Ich habe das nun zum Laufen gebracht, es gibt aber ein Problem.
In meiner CONTAO-Installation habe ich die Anzeige des Suffixes ".html" deaktiviert.
Der von der Erweiterung erzeugte Link zum Download enthält aber den suffix ".html".
Das Anklicken das Links erzeugt nun eine 404 Seite.
Gibt es hierfür eine Lösung oder muss ich, um die Erweiterung zu nutzen, den Suffix ".html" wieder aktivieren?

Vielen Dank!

**Comment by eS-IT** [comment]
Der Link wird beim Absenden des Formulars erzeugt. Die Erweiterung verwendet den Suffix aus den Einstellungen von Contao:

https://github.com/eS-IT/downloadmail/blob/master/Classes/Services/Helper/StringHelper.php#L135

```php
$strUrl .= $strAlias . $GLOBALS['TL_CONFIG']['urlSuffix'];
```
Wenn dort kein Suffix eingetragen ist, sollte auch keiner verwendet werden.

**Comment by kissinger999** [comment]
Hallo Patrick,

im Startpunkt meiner Seite ist das Feld URL-Suffix leer. Muss ich das noch anderswo anpassen um die globale Variable  $GLOBALS['TL_CONFIG']['urlSuffix'] zu beeinflussen?

**Comment by eS-IT** [comment]
Ich sehe das Problem: das Feld URL-Suffix aus dem Startpunkt wird nicht berücksichtigt, da es dies bei der Entwicklung der Erweiterung noch nicht gab. Das Suffix wurde früher in den Systemeinstellungen von Contao verwaltet. Diese Einstellung gibt es scheinbar nicht mehr.

Das Suffix lässt sich also im Augenblick nicht abschalten.

**Comment by kissinger999** [comment]
Danke Patrick und weiterhin alles Gute!
Schön dass es solche Spezis wie dich gibt!

**Comment by operatorone** [comment]
Hi, ich habe auch das Problem, dass ich ein leeres Suffix habe. Kann ich das eventuell per Contao/DCA oder anderweitig anpassen, sodass kein ".html" mehr angehängt wird? Vielleicht sogar upatesicher?

**Comment by eS-IT** [comment]
Leider nein, es sind größere Änderungen am Code nötig. Das Problem ist, dass das Suffix jetzt pro Seite und nicht mehr global angegeben wird. Die Seite mit dem Download muss aber nicht unterhalb der selben Startseite liegen, wie das Formular. Da es auch das Download-Element mehrfach und unter mehreren Startseiten geben kann, habe ich keine Möglichkeit, die richtige Startseite zu bestimmen. Ich kann deshalb auch nicht das richtige Suffix bestimmen. Auch wenn es unwahrscheinlich ist, dass in einer Installation abweichende Suffixes verwendet werden, ist raten nicht zielführend.

Einzige Lösung wäre, ein Feld in den Einstellungen zu erstellen, mit dem man das Suffix für die Downloads manuell festlegen kann. Dann wäre man aber auch auf eins beschränkt und man müsste es doppelt pflegen. Keine schöne Lösung aber möglich. Wenn ich Zeit finde baue ich es gerne ein, wenn Euch diese Lösung reicht.  Wie das bei Open Source so ist, Umsetzung wenn Zeit ist.

**Comment by operatorone** [comment]
Ja, das wäre auf jeden Fall schon mal eine prima Lösung und bietet maximale Flexibilität. Richtig, es wäre redundant zu den Systemeinstellungen, aber ich denke, wenn man es in der Doku entsprechend erwähnt, dann ist das ohne Weiteres machbar. 

Würde mich sehr freuen, wenn du das umsetzen könntest. Gerne spende ich auch was dafür oder du schickst mir eine Rechnung 🙂.
